### PR TITLE
newest n8n.io version

### PR DESCRIPTION
**Pull request by LucaOverflow**
I've removed the version tag when installing n8n.
There is no option to update. For now you just would need to rebuild the Addon to get the latest version.
I've tried to add ingress to the addon since my server operates behind a proxy. Unfortunally I didn't got it to a working state. The n8n Server listens on 0.0.0.0 judging from the log. So Home Assistant tries to connect to that ip which is obviously not working. I've tried modifieing the n8n parameters to take an ip as well but with that I just got more errors.
I just need it for a very simple automation so this ist working enough for me. Maybe someone will trie to get it working.

### CODE REVIEW

**Comment by Rbillon59** [comment]
Hi Lucas, thanks you for your PR, I'll check it out when I'll have a bunch of time

**Comment by Rbillon59** [comment]
Just checked. So, there is two subjects here :

1. Removing the n8n version in the dockerfile to have always the latest version of n8n

I disagree with this, it's pretty for the same reason you should not use the :latest tags on your docker image. if you always use the latest version, you're not sure every installations would be the same, you wouldn't be sure there is no breaking change etc... So I'll try to regurlaly bump the n8n version in the Dockerfile with a bit of local tests.

2. Accessing n8n from a reverse proxy.

I just tried on my personnal instance. As per I exposed the application, it's recheable from http(s)://<hass_ip>:5678 so if your reverse proxy can access your hassio instance on port 8123, I guess it sould reach the 5678 port. Just be careful with the protocol, I had an issue when setting the protocol as http in the config, when using the UI button to get to the service, it always tried https.

**Comment by LucaOverflow** [comment]
I agree with you on the first issue. But like you said it requires manual Labour from you or any other participants. The current version in the docker file is pretty old and I needed a newer version since the integration I wanted to use didn't exist in the old one. Maybe the best way to tackle this is to use a config entry for the version you wanna use.

On the second topic: it's not that I couldn't get it to work with the according forwarding or proxy settings but more a convenience feature. I like the ingress feature since you have everything you need in one interface and don't need to configure your router on every new addon.

For now this isn't really relevant for me anyways since the integration I wanted to use is not functional for what I wanted to do with it. So until this changes I don't need n8n.

**Comment by Rbillon59** [comment]
Version have been bumped to 0.134.0

For the proxy part, can you open an issue with details about how your system work to reproduce it locally and try to fix it ?

Sorry for the delay, I've been busy for a while. 
I'll close the PR for now. Thanks you for your contribution to the addon

**Pull request closed without merging**
